version: '3.4'

services:
  coviddashboard:
    image: coviddashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4100:4000
